### ISSUE TITLE
Upgrading from `v0.7.0` to `v0.8.0` makes the `ACTION: 'print'` time out

### ISSUE THREAD

**Issue by jvrplmlmn** [grafana/cortex-rules-action#19]
After upgrading our GitHub Actions to use `v0.8.0` (from `v0.7.0`), the step that run `ACTION: 'print'`, such as:

```
      - name: Print rules
        uses: grafana/cortex-rules-action@v0.7.0
        env:
          ACTION: 'print'
```

went from ~5s to timing out (in our case, 10 minutes).

Diffing the tags: https://github.com/grafana/cortex-rules-action/compare/v0.7.0...v0.8.0, the only relevant change seems to be 
 https://github.com/grafana/cortex-rules-action/pull/16/files#r669389182
